RetoCursos/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.urls import re_path as url
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path
from django.contrib.auth import views as auth_views

from PruebaTecnica import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name="login"),
    path('', views.logout_view, name="logout"),
    path('index/', views.index, name="index"),
    path('profile/', views.profile, name="profile"),
    path('post/ajax/loginUser', views.loginUser, name='loginUser'),

    url(r'^cursos/(?P<pk>[0-9]+)/$', views.listadocursos, name="cursos"),

    path('estudiante/', views.gestionarestudiante, name="gestionarestudiante"),
    path('ajax/crud/createStudent/',  views.CreateCrudEstudiante.as_view(), name='crud_ajax_create_estudiante'),
    path('ajax/crud/updateStudent/',  views.UpdateCrudEstudiante.as_view(), name='crud_ajax_update_estudiante'),
    path('ajax/crud/deleteStudent/', views.DeleteCrudEstudiante.as_view(), name='deleteStudent'),

    path('curso/', views.gestionarcurso, name="gestionarcurso"),
    path('ajax/crud/createCourse/',  views.CreateCrudCurso.as_view(), name='crud_ajax_create_curso'),
    path('ajax/crud/updateCourse/',  views.UpdateCrudCurso.as_view(), name='crud_ajax_update_curso'),
    path('ajax/crud/deleteCurso/', views.DeleteCrudCurso.as_view(), name='deleteCurso'),

    path('inscripciones/', views.gestionarInscripcion, name="gestionarinscripciones"),
    path('registrarInscripcion/', views.RegistrarInsrcripcion, name="registrarInscripcion"),
    path('ajax/crud/deleteInscripcion/', views.DeleteCrudInscripcionCurso.as_view(), name='deleteInscripcion'),

    re_path(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),

    re_path(
        r'^nombre-estudiante-autocomplete/$',
         views.NombreEstudianteAutocomplete.as_view(),
        name='nombre-estudiante-autocomplete',
    ),

    re_path(
        r'^nombre-curso-autocomplete/$',
         views.NombreCursoAutocomplete.as_view(),
        name='nombre-curso-autocomplete',
    ),
    
]+ static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

PruebaTecnica/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

# Create your models here.

class Curso(models.Model):
    nombre = models.CharField(max_length=60)
    horario_inicio = models.TimeField()
    horario_fin = models.TimeField()
    fechaInicio = models.DateField()
    fechaFin = models.DateField()
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'curso'
        managed = True
        
    def __str__(self):
        return self.nombre


class Estudiante(models.Model):
    nombre = models.CharField(max_length=60)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    edad = models.IntegerField()
    email = models.EmailField()
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'estudiante'
        managed = True
        
    def __str__(self):
        return self.nombre
    


class DetalleInscripcion(models.Model):
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'detalle_inscripcion'
        managed = True

templates/dashboard.html
{% extends "index.html" %}

{% load static %}

{% block content %}

<div class="pd-20 card-box mb-30">

<div class="title pb-20">
    <h2 class="h3 mb-0">Reportes del Colegio de Retos</h2>
</div>

<div class="clearfix">
    <div class="pull-left">
        <h4 class="text-blue h4">TOP 3 de Cursos con más estudiantes en los últimos 6 meses</h4>
        <p class="mb-30"></p>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="id_table_inscripcion">
        <thead>
            <tr>
                <th scope="col" style="text-align: center;">Cursos</th>
                <th scope="col" style="text-align: center;">Cant. Matriculados</th>
            </tr>
        </thead>
        <tbody>
            {% for c in cursostop %}
                <tr id="inscripcion-{{c.id}}">
                    <td scope="row" style="text-align: center;">
                        {{ c.curso__nombre }}   
                    </th>
                    <td scope="row" style="text-align: center;">
                        {{ c.num_estudiantes }}
                    </th>
                   
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="clearfix">
    <div class="pull-left">
        <h4 class="text-blue h4">Listado de Estudiantes y sus Cursos</h4>
        <p class="mb-30"></p>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="id_table_inscripcion">
        <thead>
            <tr>
                <th scope="col" style="text-align: center;">Estudiantes</th>
                <th scope="col" style="text-align: center;">Nro. Cursos</th>

                <th scope="col" style="text-align: center;"></th>
            </tr>
        </thead>
        <tbody>
            {% for e in estudiantes %}
                <tr id="inscripcion-{{e.id}}">
                    <td scope="row" style="text-align: center;">
                        {{ e.estudiante__nombre }} {{ e.estudiante__apellido_paterno }} {{ e.estudiante__apellido_materno }}  
                    </th>
                    <td scope="row" style="text-align: center;">
                        {{ e.num_cursos }} 
                    </th>

                    <td align="center">
                        <button class="btn btn-success" onClick="location.href='{% url 'cursos' pk=e.estudiante_id %}'"><i class="icon-copy bi bi-pencil-square"></i></button>
                    </td>
                   
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

</div>
{% endblock %}

templates/forgot-password.html
<!DOCTYPE html>
<html>
	<head>
		<!-- Basic Page Info -->
		<meta charset="utf-8" />
		<title>DeskApp - Bootstrap Admin Dashboard HTML Template</title>

		<!-- Site favicon -->
		<link
			rel="apple-touch-icon"
			sizes="180x180"
			href="vendors/images/apple-touch-icon.png"
		/>
		<link
			rel="icon"
			type="image/png"
			sizes="32x32"
			href="vendors/images/favicon-32x32.png"
		/>
		<link
			rel="icon"
			type="image/png"
			sizes="16x16"
			href="vendors/images/favicon-16x16.png"
		/>

		<!-- Mobile Specific Metas -->
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, maximum-scale=1"
		/>

		<!-- Google Font -->
		<link
			href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
			rel="stylesheet"
		/>
		<!-- CSS -->
		<link rel="stylesheet" type="text/css" href="vendors/styles/core.css" />
		<link
			rel="stylesheet"
			type="text/css"
			href="vendors/styles/icon-font.min.css"
		/>
		<link rel="stylesheet" type="text/css" href="vendors/styles/style.css" />

		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script
			async
			src="https://www.googletagmanager.com/gtag/js?id=G-GBZ3SGGX85"
		></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag() {
				dataLayer.push(arguments);
			}
			gtag("js", new Date());

			gtag("config", "G-GBZ3SGGX85");
		</script>
		<!-- Google Tag Manager -->
		<script>
			(function (w, d, s, l, i) {
				w[l] = w[l] || [];
				w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
				var f = d.getElementsByTagName(s)[0],
					j = d.createElement(s),
					dl = l != "dataLayer" ? "&l=" + l : "";
				j.async = true;
				j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
				f.parentNode.insertBefore(j, f);
			})(window, document, "script", "dataLayer", "GTM-NXZMQSS");
		</script>
		<!-- End Google Tag Manager -->
	</head>

	<body>
		<div class="login-header box-shadow">
			<div
				class="container-fluid d-flex justify-content-between align-items-center"
			>
				<div class="brand-logo">
					<a href="login.html">
						<img src="vendors/images/deskapp-logo.svg" alt="" />
					</a>
				</div>
				<div class="login-menu">
					<ul>
						<li><a href="#">Login</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div
			class="login-wrap d-flex align-items-center flex-wrap justify-content-center"
		>
			<div class="container">
				<div class="row align-items-center">
					<div class="col-md-6">
						<img src="vendors/images/forgot-password.png" alt="" />
					</div>
					<div class="col-md-6">
						<div class="login-box bg-white box-shadow border-radius-10">
							<div class="login-title">
								<h2 class="text-center text-primary">Forgot Password</h2>
							</div>
							<h6 class="mb-20">
								Enter your email address to reset your password
							</h6>
							<form>
								<div class="input-group custom">
									<input
										type="text"
										class="form-control form-control-lg"
										placeholder="Email"
									/>
									<div class="input-group-append custom">
										<span class="input-group-text"
											><i class="fa fa-envelope-o" aria-hidden="true"></i
										></span>
									</div>
								</div>
								<div class="row align-items-center">
									<div class="col-5">
										<div class="input-group mb-0">
											<!--
											use code for form submit
											<input class="btn btn-primary btn-lg btn-block" type="submit" value="Submit">
										-->
											<a
												class="btn btn-primary btn-lg btn-block"
												href="index.html"
												>Submit</a
											>
										</div>
									</div>
									<div class="col-2">
										<div
											class="font-16 weight-600 text-center"
											data-color="#707373"
										>
											OR
										</div>
									</div>
									<div class="col-5">
										<div class="input-group mb-0">
											<a
												class="btn btn-outline-primary btn-lg btn-block"
												href="login.html"
												>Login</a
											>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- welcome modal start -->
		<div class="welcome-modal">
			<button class="welcome-modal-close">
				<i class="bi bi-x-lg"></i>
			</button>
			<iframe
				class="w-100 border-0"
				src="https://embed.lottiefiles.com/animation/31548"
			></iframe>
			<div class="text-center">
				<h3 class="h5 weight-500 text-center mb-2">
					Open source
					<span role="img" aria-label="gratitude">❤️</span>
				</h3>
				<div class="pb-2">
					<a
						class="github-button"
						href="https://github.com/dropways/deskapp"
						data-color-scheme="no-preference: dark; light: light; dark: light;"
						data-icon="octicon-star"
						data-size="large"
						data-show-count="true"
						aria-label="Star dropways/deskapp dashboard on GitHub"
						>Star</a
					>
					<a
						class="github-button"
						href="https://github.com/dropways/deskapp/fork"
						data-color-scheme="no-preference: dark; light: light; dark: light;"
						data-icon="octicon-repo-forked"
						data-size="large"
						data-show-count="true"
						aria-label="Fork dropways/deskapp dashboard on GitHub"
						>Fork</a
					>
				</div>
			</div>
			<div class="text-center mb-1">
				<div>
					<a
						href="https://github.com/dropways/deskapp"
						target="_blank"
						class="btn btn-light btn-block btn-sm"
					>
						<span class="text-danger weight-600">STAR US</span>
						<span class="weight-600">ON GITHUB</span>
						<i class="fa fa-github"></i>
					</a>
				</div>
				<script
					async
					defer="defer"
					src="https://buttons.github.io/buttons.js"
				></script>
			</div>
			<a
				href="https://github.com/dropways/deskapp"
				target="_blank"
				class="btn btn-success btn-sm mb-0 mb-md-3 w-100"
			>
				DOWNLOAD
				<i class="fa fa-download"></i>
			</a>
			<p class="font-14 text-center mb-1 d-none d-md-block">
				Available in the following technologies:
			</p>
			<div class="d-none d-md-flex justify-content-center h1 mb-0 text-danger">
				<i class="fa fa-html5"></i>
			</div>
		</div>
		<button class="welcome-modal-btn">
			<i class="fa fa-download"></i> Download
		</button>
		<!-- welcome modal end -->
		<!-- js -->
		<script src="vendors/scripts/core.js"></script>
		<script src="vendors/scripts/script.min.js"></script>
		<script src="vendors/scripts/process.js"></script>
		<script src="vendors/scripts/layout-settings.js"></script>
		<!-- Google Tag Manager (noscript) -->
		<noscript
			><iframe
				src="https://www.googletagmanager.com/ns.html?id=GTM-NXZMQSS"
				height="0"
				width="0"
				style="display: none; visibility: hidden"
			></iframe
		></noscript>
		<!-- End Google Tag Manager (noscript) -->
	</body>
</html>

templates/gestionarinscripcion.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="title pb-20">
        <h2 class="h3 mb-0">Gestionar Inscripciones</h2>
    </div>

    {% for message in messages %}
    <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000" style="margin-right: auto; margin-left: auto">
      <div class="toast-header" >
        <strong class="mr-auto">
          {% if message.tags == 'error' %}
            <i class="fas fa-times mr-2"></i>
          {% elif message.tags == 'warning' %}
            <i class="fas fa-exclamation mr-2"></i>
          {% elif message.tags == 'info' %}
            <i class="fas fa-info mr-2"></i>
          {% elif message.tags == 'success' %}
            <i class="fas fa-check mr-2"></i>
          {% endif %}
          {{message.tags|capfirst}}
        </strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        {{message|safe}}
      </div>
    </div>
  {% endfor %}
  
    <div class="pd-20 card-box mb-30">
        <div class="clearfix">
            <div class="pull-left">
                <h4 class="text-blue h4">Gestionar Inscripciones</h4>
                <p class="mb-30"></p>
            </div>
        </div>

        
    
            <div class="form-group row" style="float: right;">
                <div class="col">
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#formInscripcion">
                        Agregar Nueva Inscripcion
                      </button>
                </div>
            </div>
           
            <div class="table-responsive">
                <table class="table table-striped" id="id_table_inscripcion">
                    <thead>
                        <tr>
                            <th scope="col" style="text-align: center;">Estudiante</th>
                            <th scope="col" style="text-align: center;">Curso Registrado</th>
                            
                            <th scope="col" style="text-align: center;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for inscripcion in page %}
                            <tr id="inscripcion-{{inscripcion.id}}">
                                <td scope="row" style="text-align: center;">
                                    {{ inscripcion.estudiante.nombre }} {{ inscripcion.estudiante.apellido_paterno }}  {{ inscripcion.estudiante.apellido_materno }}  
                                </th>
                                <td scope="row" style="text-align: center;">
                                    {{ inscripcion.curso }}
                                </th>
                               
                                <td scope="row">
                                    <button type="button"
                                            class="btn btn-danger btn-lg"
                                            data-toggle="modal"
                                            onClick="deleteInscripcion({{ inscripcion.id }})">
                                        <i class="icon-copy bi bi-trash3-fill"></i>
                                    </button>
                                 
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        {% if page.has_other_pages %}
            <div class="col-lg-12"
                 style="justify-content: center;
                        align-items: center;
                        display: flex;">
                <div class="dataTables_paginate paging_simple_numbers"
                     id="example2_paginate">
                    <ul class="pagination">
                        <li class="paginate_button page-item previous {% if not prev_url %} disabled{% endif %}">
                            <a href="{{ prev_url }}"
                               aria-disabled="true"
                               tabindex="-1"
                               class="page-link">Anterior</a>
                        </li>
                        {% for n in page.paginator.page_range %}
                            {% if page.number == n %}
                                <li class="paginate_button page-item active">
                                    <a href="?page={{ n }}"
                                       class="page-link">{{ n }}
                                        <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            {% elif n > page.number|add:-6 and n < page.number|add:6 %}
                                <li class="paginate_button page-item active">
                                    <a href="?page={{ n }}"
                                       class="page-link">{{ n }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <li class="paginate_button page-item {% if not next_url %} disabled{% endif %}">
                            <a href="{{ next_url }}"
                               class="page-link">Siguiente</a>
                        </li>
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>

    <!-- Modal -->
  <div class="modal fade" id="formInscripcion" tabindex="-1" role="dialog" aria-labelledby="formCursoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="formInscripcion">Nueva Inscripcion</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form id="fnuevaInscripcion" name="fnuevaInscripcion" action ="{% url 'registrarInscripcion' %}"
        method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-body">
            <div class="form-group">
              <label for="estudiante" class="col-form-label">Estudiante:</label>
              <select class="custom-select" id="id_estudiante" name="estudianteid" >
                <option selected="" value="0">
                    Selecciona el Estudiante
                </option>
                {% for e in estudiantes  %}
                    <option value="{{ e.id }}">
                        {{ e.apellido_paterno }} {{ e.apellido_materno }}, {{ e.nombre }}
                    </option>
                {% endfor %}
            </select>
            </div>
            <div class="form-group">
                <label for="curso" class="col-form-label">Curso:</label>
                <select class="custom-select" id="id_curso" name="cursoid" >
                    <option selected="" value="0">
                        Selecciona el Curso
                    </option>
                    {% for c in cursos  %}
                        <option value="{{ c.id }}">
                            {{ c.nombre }}, {{ e.horario_inicio }} - {{ e.horario_fin }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-success">Registrar</button>
        </div>
    </form>
      </div>
    </div>
  </div>

     <!--- MODAL ELIMINAR INSCRIPCION -->
  <div class="modal fade"
  id="elimiar-inscripcion"
  tabindex="-1"
  role="dialog"
  aria-hidden="true">
 <div class="modal-dialog modal-dialog-centered" role="document">
     <div class="modal-content">
         <div class="modal-body text-center font-18">
             <form id="form-delete-inscripcion" action ="">
                 <h4 class="padding-top-30 mb-30 weight-500">
                     Estas seguro que quieres eliminar la Inscripcion?
                 </h4>
                 <div class="padding-bottom-30 row"
                      style="max-width: 170px; margin: 0 auto">
                     <div class="col-6">
                         <button type="button"
                                 class="btn btn-secondary border-radius-100 btn-block confirmation-btn"
                                 data-dismiss="modal">
                             <i class="fa fa-times"></i>
                         </button>
                         NO
                     </div>
                     <div class="col-6">
                         <button type="submit"
                                 class="btn btn-primary border-radius-100 btn-block confirmation-btn">
                             <i class="fa fa-check"></i>
                         </button>
                         SI
                     </div>
                 </div>
             </form>
         </div>
     </div>
 </div>
</div>


    <script>
        function deleteInscripcion(id) {
            $('#elimiar-inscripcion').modal('show');

            $(function() {
                $("#form-delete-inscripcion").on('submit',function(e){
                    
                    $("#elimiar-inscripcion").modal("hide");
                    e.preventDefault();
                    
                    //submit the form
                    $.ajax({
                        url: '{% url 'deleteInscripcion'  %}'  ,
                        data: {
                            'id': id,
                        },
                        dataType: 'json',
                        success: function (data) {
                            
                            if (data.deleted) {
                              $("#id_table_inscripcion #inscripcion-" + id).remove();
                            }
                        }
                    });
                });
            });
          }
    </script>
{% endblock content %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>

	{% include "include/head.html" %}

	{% block head %}
	{% endblock %}

	<body>
	
		<div class="header">
			<div class="header-left">
				<div class="menu-icon bi bi-list">
					
				</div>
			</div>
			<div class="header-right">
				
			
				<div class="user-info-dropdown">
					<div class="dropdown">
						<a
							class="dropdown-toggle"
							href="#"
							role="button"
							data-toggle="dropdown"
						>
							<span class="user-icon">
								<img src="{% static 'vendors/images/user.svg' %}" alt="" />
							</span>
							{% if user.is_authenticated %}
							<span class="user-name">{{ user.first_name }}</span>
							{% endif %}
						</a>
						<div
							class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list"
						>
							
						
							<a class="dropdown-item" href="{% url 'logout' %}"
								><i class="dw dw-logout"></i> Cerrar Sesion</a
							>
						</div>
					</div>
				</div>
				
			</div>
		</div>

		<div class="right-sidebar">
			<div class="sidebar-title">
				<h3 class="weight-600 font-16 text-blue">
					Layout Settings
					<span class="btn-block font-weight-400 font-12"
						>User Interface Settings</span
					>
				</h3>
				<div class="close-sidebar" data-toggle="right-sidebar-close">
					<i class="icon-copy ion-close-round"></i>
				</div>
			</div>
		
		</div>

		<div class="left-side-bar">
			<div class="brand-logo">
				<a href="{% url 'index' %}">
		
					<img src="{% static 'logo.png' %}" width="50", height="50" />
					
					<label style="font-size:15px; margin-left:2px; margin-top:5px; display: inline-block"> Colegio de Retos
				</a>
				<div class="close-sidebar" data-toggle="left-sidebar-close">
					<i class="ion-close-round"></i>
				</div>
			</div>
			<div class="menu-block customscroll">
				<div class="sidebar-menu">
					<ul id="accordion-menu">
						<li class="dropdown">
							<a href="javascript:;" class="dropdown-toggle">
								<span class="micon bi bi-house"></span
								><span class="mtext">Incio</span>
							</a>
							<ul class="submenu">
								<li><a href="{% url 'index' %}">Dashboard</a></li>
		
							</ul>
						</li>
						<li class="dropdown">
							<a href="javascript:;" class="dropdown-toggle">
								<span class="micon bi bi-textarea-resize"></span
								><span class="mtext">Mantenimientos</span>
							</a>
							<ul class="submenu">
								<li><a href="{% url 'gestionarestudiante'%}">Gestionar Estudiantes</a></li>
								<li>
									<a href="{% url 'gestionarcurso'%}">Gestionar Cursos</a>
								</li>
								<li><a href="{% url 'gestionarinscripciones'%}">Gestionar Inscripciones</a></li>
							</ul>
						</li>
				
					
					
					</ul>
				</div>
			</div>
		</div>
		<div class="mobile-menu-overlay"></div>

		<div class="main-container">
			<div class="xs-pd-20-10 pd-ltr-20">

				{% block content %}



				{% endblock %}

				
			</div>
		</div>

	
		{% block js  %}
		
		

		{% endblock js  %}
	
		<!-- js -->
		{% include 'include/footerjs.html' %}
	</body>
</html>

templates/listado_cursos.html
{% extends "index.html" %}

{% load static %}

{% block content %}

<div class="pd-20 card-box mb-30">

<div class="title pb-20">
    <h2 class="h3 mb-0">Reportes del Colegio de Retos</h2>
</div>

<div class="clearfix">
    <div class="pull-left">
        <h4 class="text-blue h4">Listado de Cursos del Estudiante: {{ estudiante.nombre}}</h4>
        <p class="mb-30"></p>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="id_table_inscripcion">
        <thead>
            <tr>
                <th scope="col" style="text-align: center;">Curso</th>
                <th scope="col" style="text-align: center;">Fecha Inicio - Fecha Fin</th>
                <th scope="col" style="text-align: center;">Horarios</th>
            </tr>
        </thead>
        <tbody>
            {% for c in cursos %}
                <tr id="inscripcion-{{c.id}}">
                    <td scope="row" style="text-align: center;">
                        {{ c.curso__nombre }}   
                    </th>
                    <td scope="row" style="text-align: center;">
                        {{ c.curso__fechaInicio|date:"Y-m-d" }}   -   {{c.curso__fechaFin|date:"Y-m-d" }}
                    </th>
                    <td scope="row" style="text-align: center;">
                        {{ c.curso__horario_inicio|time:"h:i a" }}   -   {{ c.curso__horario_fin|time:"h:i a" }}
                    </th>
                   
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


</div>
{% endblock %}